### PR TITLE
Split SilverStripeIcons class to own package

### PR DESCRIPTION
**Pull request by Zerogiven**
Maybe you like the idea like me to split the silverstripe icon class to it's own package. I need them often, especially for ModelAdmins but not always using the cms actions package, so i made a tiny package with three little helper classes which are just a big bunch of constants like you have at your SilverStripeIcons class. I just automated things a bit like reading the font svg directly from the silverstripe admin package and generate my classes so i can not miss any icon for any version. I also tagged the package equally to the silverstripe admin package. Another thing i've done is that i generate three classes... One with just the icon names (like your class), one with the icon names and the "font-icon-" prefix, and one with the unicode character. All classes have the same constants.

However, if you dislike this idea just remove the pull request and keep your package like it is, good work anyway :)

cheers

### CODE REVIEW

**Comment by lekoala** [comment]
@Zerogiven I really like the idea. It seemed overkill at the time to create a package just for that but at the same time, I'm also using it in other places like in my silverstripe-base module. So it makes sense!
Maybe one minor thing would be to add a class_alias in order to avoid breaking stuff for those updating ?

**Comment by Zerogiven** [comment]
@lekoala The only problem is that i did not prefixed the constant names with "ICON_" like you did... so the class alias will not work like expected.

What i can do is to rewrite your SilverStripeIcons class to use the defined constants from the package so it will not break updates.

Another solution could be generating the classes with other constant names (prefixed with "ICON_") but this is not the way i like ;)

Third option would be generating a fourth class inside my package which can handle as class_alias

... for  now the cleanest and easiest way is option one. I update the pull request, if you have a better idea  just tell me :D

**Comment by lekoala** [comment]
agreed the ICON_ prefix is really just there in case the name of an icon would result in an invalid constant name. it's not the case (yet) but on another project where i did something similar where more icons where involved I ended up with issues without the prefix

**Comment by lekoala** [comment]
@Zerogiven so i'm not going to merge this for now, i'm not sure of the add value to add a dependency just for a couple of css classes. Maybe I'll just drop my own SilverStripeIcons class and reference yours if a future version.
users are always free to use your module in their own projects if needed (happy to add a mention to the readme if you send a PR)

**Pull request closed without merging**
